# Generated by Django 4.1.4 on 2023-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
